import os

# auth
PING_CODE_CLIENT_ID = os.environ['PING_CODE_CLIENT_ID']
PING_CODE_CLIENT_SECRET = os.environ['PING_CODE_CLIENT_SECRET']

PING_CODE_PRODUCT_NAME = os.environ['PING_CODE_PRODUCT_NAME']
PING_CODE_PRODUCT_SERVER = os.environ['PING_CODE_PRODUCT_SERVER']

PING_CODE_REPO_NAME = os.environ['PING_CODE_REPO_NAME']
PING_CODE_REPO_FULL_NAME = os.environ['PING_CODE_REPO_FULL_NAME']
PING_CODE_REPO_OWNER_NAME = os.environ['PING_CODE_REPO_OWNER_NAME']
PING_CODE_REPO_IS_FORK = os.environ['PING_CODE_REPO_IS_FORK']
PING_CODE_REPO_IS_PRIVATE = os.environ['PING_CODE_REPO_IS_PRIVATE']
PING_CODE_REPO_HTML_URL = f'{PING_CODE_PRODUCT_SERVER}/{PING_CODE_REPO_FULL_NAME}'
PING_CODE_REPO_BRANCHES_URL = f'{PING_CODE_REPO_HTML_URL}/src/' + '{branch}'
PING_CODE_REPO_COMMITS_URL = f'{PING_CODE_REPO_HTML_URL}/commit/' + '{sha}'
PING_CODE_REPO_PULLS_URL = f'{PING_CODE_REPO_HTML_URL}/pulls/' + '{number}'
